// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreTestApi
{
    public partial class Test
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}