// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MvcTest.Models
{
    public partial class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }
}